# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://novahale.com
title: Novahale Technologies
email: info@novahale.com
author: Bekir Oguz
description: Novahale Technologies BV is your trustable partner in building enterprise system integrations, high traffic distributed services, etc...
copyright: 'Copyright &copy; 2016 Novahale Technologies BV. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/bekiroguzz
  - title: github
    url: https://github.com/novahale
  - title: email
    url: mailto:info@novahale.com
#  - title: linkedin
#    url:
